/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.major;

import coreEngine.Seed;

/**
 *
 * @author jltrask
 */
public class UserIOTableDisplay extends javax.swing.JPanel {

    private Seed seed;

    /**
     * Creates new form UserIOTableDisplay
     */
    public UserIOTableDisplay() {
        initComponents();

    }

    public void activate(MainWindowUser mainWindow) {        
        seed = mainWindow.getActiveSeed();
        
    }
    
    public TableDisplaySegmentATM getTableDisplaySegmentATM() {
        return this.tableDisplaySegmentATM;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        tableDisplaySegmentATM = new GUI.major.TableDisplaySegmentATM();
        facilityATMJPanel2 = new GUI.major.FacilityATMJPanel();

        jSplitPane1.setDividerLocation(115);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLeftComponent(tableDisplaySegmentATM);
        jSplitPane1.setRightComponent(facilityATMJPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.major.FacilityATMJPanel facilityATMJPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private GUI.major.TableDisplaySegmentATM tableDisplaySegmentATM;
    // End of variables declaration//GEN-END:variables
}
